interface FbEventOptions {
  eventName: string; // ViewContent, AddToCart, InitiateCheckout, Purchase, etc.
  eventId?: string; // Optional, unique event id's will be generated by default
  emails?: string[]; // Optional
  phones?: string[]; // Optional
  firstName?: string; // Optional
  lastName?: string; // Optional
  country?: string; // Optional
  city?: string; // Optional
  zipCode?: string; // Optional
  products?: Array<{
    sku: string;
    quantity: number;
  }>; // Optional
  value?: number; // Optional
  currency?: string; // Optional
  enableStandardPixel?: boolean; // Optional (for future pixel integration)
}

import { apiRequest } from "@/lib/api-client";

/**
 * Send a Facebook Conversion API event
 *
 * This function sends events to /api/fb-events endpoint which handles
 * server-side event tracking via Meta Conversions API.
 *
 * The API route handles:
 * - Event deduplication using event_id
 * - Server-side event tracking via Conversions API
 * - User data hashing for privacy compliance
 */
export async function fbEvent(options: FbEventOptions): Promise<void> {
  try {
    // Only run on client-side
    if (typeof window === "undefined") {
      console.warn("[FB Tracking] fbEvent can only be called from client-side");
      return;
    }

    // Send event to our API route which handles the Meta Conversions API call
    await apiRequest<any>("POST", "/fb-events", {
      eventName: options.eventName,
      eventId: options.eventId,
      emails: options.emails,
      phones: options.phones,
      firstName: options.firstName,
      lastName: options.lastName,
      country: options.country,
      city: options.city,
      zipCode: options.zipCode,
      products: options.products,
      value: options.value,
      currency: options.currency,
    });
  } catch (error) {
    console.error("[FB Tracking] Error sending Facebook event:", error);
    // Fail silently to not break user experience
  }
}

/**
 * Check if Facebook Pixel is enabled and configured
 */
export async function isFbTrackingEnabled(): Promise<boolean> {
  try {
    const adsConfig = await apiRequest<any>("GET", "/ads-config");
    return (
      adsConfig.metaPixel?.enabled === true && !!adsConfig.metaPixel?.pixelId && adsConfig.metaPixel?.serverSideTracking?.enabled === true
    );
  } catch {
    return false;
  }
}
